alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: pianosim.unlikeotherai.com
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: api
    match:
      authority:
        exact: pianosim.unlikeotherai.com
      path:
        prefix: /
name: piano-sim
region: lon
services:
- build_command: corepack enable pnpm && pnpm install --frozen-lockfile
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
    value: EV[1:uEatIx1S60WppSxPfe31xncQMIdk330d:EgINQkxDVzvGq7qZhIb461quct9saPqVDi7GA2HMYLIRQ6k8LghepCTU+xVZlh0aK7jbTsvAVoz6aWo3ZjXt9sZPTPAutLcqpe2OgsvnGvqP69wK+hYox8fhJnsSWcz4ftzglpLD27VcS7q5S3yEwZeMQN96zTCiIfG9sjvaeBWpweDkYedSEytn]
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  github:
    branch: main
    deploy_on_push: true
    repo: UnlikeOtherAI/PianoPOSSimulator
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: api
  run_command: pnpm start
  source_dir: API
